"""add embedding vector to chunks

Revision ID: 9c542b3e51c2
Revises: cad7872da278
Create Date: 2026-03-01 09:08:44.623953

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = "9c542b3e51c2"
down_revision: Union[str, Sequence[str], None] = "cad7872da278"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chunks", sa.Column("embedding", Vector(1536), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chunks", "embedding")
    # ### end Alembic commands ###
