"""add agent_node_traces table

Revision ID: ef967ddd61ba
Revises: 3912dec42070
Create Date: 2026-03-08 09:41:15.122799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef967ddd61ba'
down_revision: Union[str, Sequence[str], None] = '3912dec42070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_node_traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('node_name', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('route_to', sa.String(length=50), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_node_traces_agent_run_id'), 'agent_node_traces', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_agent_node_traces_id'), 'agent_node_traces', ['id'], unique=False)
    op.create_index(op.f('ix_agent_node_traces_node_name'), 'agent_node_traces', ['node_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_node_traces_node_name'), table_name='agent_node_traces')
    op.drop_index(op.f('ix_agent_node_traces_id'), table_name='agent_node_traces')
    op.drop_index(op.f('ix_agent_node_traces_agent_run_id'), table_name='agent_node_traces')
    op.drop_table('agent_node_traces')
    # ### end Alembic commands ###
